/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controller.AluguelController;
import models.Aluguel;
import tools.CaixaDeDialogo;
import tools.Combos;
import tools.Formatacao;

/**
 *
 * @author luis_
 */
public class CadastroAluguelView extends javax.swing.JFrame {
    
    Combos cbVeiculo, cbCliente, cbTpPag;
    Aluguel objAluguel;
    String login = LoginView.LoginUsuario.getLogin();

    /**
     * Creates new form CadastroAluguelView
     */
    public CadastroAluguelView() {
        initComponents();
        
        
        try {
            //carregar os alugueis existentes
            atualizarTabela();

            //carregar os veiculos existentes
            cbVeiculo = new Combos(jcbVeiculo);
            cbVeiculo.PreencheCombo("SELECT codveic, modelo FROM veiculo ORDER BY modelo");
            
            cbCliente = new Combos(jcbCliente);
            cbCliente.PreencheCombo("SELECT codcliente, nmcliente FROM cliente ORDER BY nmcliente");
            
            cbTpPag = new Combos(jcbTpPag);
            cbTpPag.PreencheCombo("SELECT codtppag, tipotppag FROM tppagamento ORDER BY tipotppag");

            //limparTela();
            lblUsuario.setText(LoginView.LoginUsuario.getNome());

        } catch (Exception ex) {
            CaixaDeDialogo.obterinstancia().exibirMensagem("ERRO:" + ex.getMessage());
        }
    }
    
    private void atualizarTabela() {
        try {

            AluguelController aluguelCon = new AluguelController(null, jtbAluguel);
            aluguelCon.PreencheAlugueis();
            Formatacao.colocaMascara(txtDataInicio, "##/##/####");
            Formatacao.colocaMascara(txtDataFim, "##/##/####");

        } catch (Exception ex) {
            CaixaDeDialogo.obterinstancia().exibirMensagem("ERRO:" + ex.getMessage());
        }
    }
    
    private void limparTela() {
        try {
            //LIMPAR OS CAMPOS DA TELA
            //LIBERAR O CAMPO MATRICULA
            cbVeiculo.SetaComboBox("");
            cbCliente.SetaComboBox("");
            cbTpPag.SetaComboBox("");
            txtKmInicio.setText("");
            txtKmFim.setText("");
            txtDataInicio.setText("");
            txtDataFim.setText("");
            txtVlDiaria.setText("");
            txtKmAdicional.setText("");
            txtVlTotal.setText("");
            
            //Formata o campo data de nascimento
            Formatacao.colocaMascara(txtDataInicio, "##/##/####");
            Formatacao.colocaMascara(txtDataFim, "##/##/####");
            
            atualizarTabela();

        } catch (Exception ex) {
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jcbVeiculo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jcbCliente = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jcbTpPag = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtKmInicio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtKmFim = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDataInicio = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDataFim = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        txtVlDiaria = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtKmAdicional = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtVlTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbAluguel = new javax.swing.JTable();
        btnIncluirAluguel = new javax.swing.JButton();
        btnAlterarAluguel = new javax.swing.JButton();
        btnExcluirAluguel = new javax.swing.JButton();
        btnLimparCampos = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Aluguel");

        jLabel3.setText("Veículo:");

        jcbVeiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Cliente:");

        jcbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Tipo de Pagamento:");

        jcbTpPag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("KM Inicio:");

        jLabel6.setText("KM Final:");

        txtKmFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKmFimActionPerformed(evt);
            }
        });

        jLabel7.setText("Data Inicio:");

        txtDataInicio.setText("jFormattedTextField1");

        jLabel8.setText("Data Fim:");

        txtDataFim.setText("jFormattedTextField1");

        jLabel9.setText("Valor Diária:");

        txtVlDiaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVlDiariaActionPerformed(evt);
            }
        });

        jLabel10.setText("Valor KM Adicional:");

        jLabel11.setText("Valor Total:");

        jtbAluguel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbAluguel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbAluguelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbAluguel);

        btnIncluirAluguel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sign-add.png"))); // NOI18N
        btnIncluirAluguel.setText("Incluir");
        btnIncluirAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirAluguelActionPerformed(evt);
            }
        });

        btnAlterarAluguel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pencil.png"))); // NOI18N
        btnAlterarAluguel.setText("Alterar");
        btnAlterarAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarAluguelActionPerformed(evt);
            }
        });

        btnExcluirAluguel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sign-delete.png"))); // NOI18N
        btnExcluirAluguel.setText("Excluir");
        btnExcluirAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirAluguelActionPerformed(evt);
            }
        });

        btnLimparCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/box.png"))); // NOI18N
        btnLimparCampos.setText("Limpar");
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });

        lblUsuario.setText("jLabel12");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtVlDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtKmAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtVlTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcbVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcbTpPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtKmInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtKmFim, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIncluirAluguel)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterarAluguel)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluirAluguel)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimparCampos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUsuario)
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jcbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jcbTpPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtKmInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtKmFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtVlDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtKmAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtVlTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIncluirAluguel)
                        .addComponent(btnAlterarAluguel)
                        .addComponent(btnExcluirAluguel)
                        .addComponent(btnLimparCampos)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtVlDiariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVlDiariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVlDiariaActionPerformed

    private void txtKmFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKmFimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKmFimActionPerformed

    private void btnIncluirAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirAluguelActionPerformed
        // TODO add your handling code here:
        try {
                if(validarDados() == true){

                    guardarDados();

                    AluguelController objAluguelCon = new AluguelController(objAluguel, null);
            
                    if (objAluguelCon.incluirAluguel(objAluguel, login) == true) {
                        CaixaDeDialogo.obterinstancia().exibirMensagem("Aluguel incluído com Sucesso!");
                    } else {
                        CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao incluir Aluguel!");
                    }
                    
                    limparTela();
                    
                }else {
                        //CaixaDeDialogo.obterinstancia().exibirMensagem("Campos inválidos"); 
                        return;
                    }
                } catch (Exception ex) {
                    CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage());
                }
    }//GEN-LAST:event_btnIncluirAluguelActionPerformed

    private void btnAlterarAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarAluguelActionPerformed
        // TODO add your handling code here:
        try {
            if(validarDados() == true){

                guardarDados();

                AluguelController objAluguelCon = new AluguelController(objAluguel, null);
                
                if (objAluguelCon.alterarAluguel() == true) {
                    CaixaDeDialogo.obterinstancia().exibirMensagem("Aluguel alterado com Sucesso!");
                } else {
                    CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao alterar Aluguel!");
                }

                limparTela();
                
                } else {
                    CaixaDeDialogo.obterinstancia().exibirMensagem("Campos inválidos"); 
                    return;
                }
                
            } catch (Exception ex) {
                CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnAlterarAluguelActionPerformed

    private void btnExcluirAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirAluguelActionPerformed
        // TODO add your handling code here:
        AluguelController objAluguelCon = new AluguelController(null, null);
        try {
            if (objAluguelCon.excluirAluguel(objAluguel) == true) {
                CaixaDeDialogo.obterinstancia().exibirMensagem("Aluguel removido com Sucesso!");
            } else {
                CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao remover Aluguel!");
            }
        } catch (Exception ex) {
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage());
        }
        
        limparTela();
    }//GEN-LAST:event_btnExcluirAluguelActionPerformed

    private void jtbAluguelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbAluguelMouseClicked
        // TODO add your handling code here:
        try {

            //pega a linha selecionada
            int linhaSelecionada = jtbAluguel.getSelectedRow();
            // Primeira coluna da linha
            String coluna1 = jtbAluguel.getModel().getValueAt(linhaSelecionada, 0).toString();

            //basta agora chamar o método buscar, passando o COLUNA1 como parâmetro de consulta
            AluguelController objAluguelCon = new AluguelController(null, null);
            objAluguel = objAluguelCon.buscarAluguel(coluna1);

            preencheCampos();

        } catch (Exception ex) {
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_jtbAluguelMouseClicked

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
        // TODO add your handling code here:
        limparTela();
    }//GEN-LAST:event_btnLimparCamposActionPerformed

    private void preencheCampos() {
        try {
            cbVeiculo.SetaComboBox(String.valueOf(objAluguel.getCodveic()));
            cbCliente.SetaComboBox(String.valueOf(objAluguel.getCodcliente()));
            cbTpPag.SetaComboBox(String.valueOf(objAluguel.getCodtppagamento()));
            //Ajusta a data para DIA/MES/ANO
            String dataFormatada1 = Formatacao.ajustaDataDMA(objAluguel.getDtinicio());
            txtDataInicio.setText(dataFormatada1);
            
            String dataFormatada2 = Formatacao.ajustaDataDMA(objAluguel.getDtfim());
            txtDataFim.setText(dataFormatada2);
            
            txtKmInicio.setText(String.valueOf(objAluguel.getKminicio()));
            txtKmFim.setText(String.valueOf(objAluguel.getKmfim()));
            txtKmAdicional.setText(String.valueOf(objAluguel.getVlkmadicional()));
            txtVlDiaria.setText(String.valueOf(objAluguel.getVldiaria()));
            txtVlTotal.setText(String.valueOf(objAluguel.getVltotal()));
            
        } catch (Exception ex) {
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage());
        }
    }

    private void guardarDados() {
        
        try {
             if (objAluguel == null) {
                objAluguel = new Aluguel();
            }
            Combos c = (Combos) jcbVeiculo.getSelectedItem();
            String codigoVeiculo = c.getCodigo();
            objAluguel.setCodveic(Integer.parseInt(codigoVeiculo));
            
            Combos d = (Combos) jcbCliente.getSelectedItem();
            String codigoCliente = d.getCodigo();
            objAluguel.setCodcliente(Integer.parseInt(codigoCliente));
            
            Combos e = (Combos) jcbTpPag.getSelectedItem();
            String codigoTpPag = e.getCodigo();
            objAluguel.setCodtppagamento(Integer.parseInt(codigoTpPag));
            
            objAluguel.setKminicio(Integer.parseInt(txtKmInicio.getText()));
            objAluguel.setKmfim(Integer.parseInt(txtKmFim.getText()));
            
            String dataFormatada1 = Formatacao.ajustaDataAMD(txtDataInicio.getText());
            String dataFormatada2 = Formatacao.ajustaDataAMD(txtDataFim.getText());
            
            objAluguel.setDtinicio(dataFormatada1);
            objAluguel.setDtfim(dataFormatada2);            
            objAluguel.setVldiaria(Double.parseDouble(txtVlDiaria.getText()));
            objAluguel.setVlkmadicional(Double.parseDouble(txtKmAdicional.getText()));
            objAluguel.setVltotal(Double.parseDouble(txtVlTotal.getText()));

        }catch(Exception ex){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Problemas no guardaDados: " + ex.getMessage());
        }
    }
    
    private boolean validarDados() {
        try {
            //VALIDAR O CAMPOS DA TELA
            //RETURN FALSE SE ALGUM CAMPO NAO ESTA PREENCHIDO CORRETAMENTE
            if(jcbVeiculo.getSelectedIndex() == 0){
                CaixaDeDialogo.obterinstancia().exibirMensagem("Selecione um Veiculo", "Atenção", 'e');
                return false;
            }
            if(jcbCliente.getSelectedIndex() == 0){
                CaixaDeDialogo.obterinstancia().exibirMensagem("Selecione um Cliente", "Atenção", 'e');
                return false;
            }
            if(jcbTpPag.getSelectedIndex() == 0){
                CaixaDeDialogo.obterinstancia().exibirMensagem("Selecione umTipo de Pagamento", "Atenção", 'e');
                return false;
            }
            if((txtKmInicio.getText().trim().equals(""))){
                CaixaDeDialogo.obterinstancia().exibirMensagem("KM Inicio Incorreto", "Atenção", 'e');
                return false;
            }
            if((txtKmFim.getText().trim().equals(""))){
                CaixaDeDialogo.obterinstancia().exibirMensagem("KM Fim Incorreto", "Atenção", 'e');
                return false;
            }
            if(txtDataInicio.getText().equals("")){
                CaixaDeDialogo.obterinstancia().exibirMensagem("Data Inicio Inválida", "Atenção", 'e');
                return false;
            }
            if(txtDataFim.getText().equals("")){
                CaixaDeDialogo.obterinstancia().exibirMensagem("Data Fim Inválida", "Atenção", 'e');
                return false;
            }
            if(txtVlDiaria.getText().equals("")){
                CaixaDeDialogo.obterinstancia().exibirMensagem("Valor de Diária Inválido", "Atenção", 'e');
                return false;
            }
            if(txtKmAdicional.getText().equals("")){
                CaixaDeDialogo.obterinstancia().exibirMensagem("Valor de KM Adicional Inválido", "Atenção", 'e');
                return false;
            }
            if(txtVlTotal.getText().equals("")){
                CaixaDeDialogo.obterinstancia().exibirMensagem("Valor Total Inválido", "Atenção", 'e');
                return false;
            }
            return true;
        } catch (Exception ex) {
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage());
            return false;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAluguelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAluguelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAluguelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAluguelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAluguelView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarAluguel;
    private javax.swing.JButton btnExcluirAluguel;
    private javax.swing.JButton btnIncluirAluguel;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> jcbCliente;
    private javax.swing.JComboBox<String> jcbTpPag;
    private javax.swing.JComboBox<String> jcbVeiculo;
    private javax.swing.JTable jtbAluguel;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JFormattedTextField txtDataFim;
    private javax.swing.JFormattedTextField txtDataInicio;
    private javax.swing.JTextField txtKmAdicional;
    private javax.swing.JTextField txtKmFim;
    private javax.swing.JTextField txtKmInicio;
    private javax.swing.JTextField txtVlDiaria;
    private javax.swing.JTextField txtVlTotal;
    // End of variables declaration//GEN-END:variables
}
